### ISSUE TITLE
Documentation and usage example

### ISSUE THREAD

**Issue by kristianmandrup** [svard/elm-phoenix#1]
Please provide some documentation for how to use this module and API and some add the sample Phoenix server code in the examples folder. Cheers!

PS: Would be nice with a collaboration with the Elm/Phoenix example by @CultivateHQ:

http://www.cultivatehq.com/posts/phoenix-elm-1/
https://github.com/CultivateHQ/seat_saver

I'd love to use this integration on my next project :)

**Comment by svard** [comment]
I think it's best if I push the entire Phoenix app as a separate repository. It can then be used as a reference.

**Comment by kristianmandrup** [comment]
Awesome! thanks :)

**Comment by svard** [comment]
I have created a more complete usage example here https://github.com/svard/hello_phoenix.

**Comment by kristianmandrup** [comment]
Thank you so much ;)
