### ISSUE TITLE
Upgrade to use elm 0.17

### ISSUE THREAD

**Issue by optikfluffel** [svard/elm-phoenix#2]
[Upgrade Guide](https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.17.md#upgrading-to-017)

**Comment by svard** [comment]
From elm 0.17 I don't think the current approach of this library is any good. You would instead write an [Effect Manager](http://guide.elm-lang.org/effect_managers/index.html) but there doesn't seem to be any good documentation available now. So for the moment I'm not planning to upgrade this library to 0.17 until it's more clear how an effect manager will work.

**Comment by optikfluffel** [comment]
Maybe the [Guide for Migrating signal usage from Elm 0.16 to 0.17](http://noredink.github.io/posts/signalsmigration.html) helps a little ^^

**Comment by svard** [comment]
There are now other packages, like http://package.elm-lang.org/packages/NoRedInk/elm-phoenix/1.0.0/, providing same functionality that are compatible with elm 0.17.
